name: Documentation Quality

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".vale.ini"
      - ".markdownlint.json"
  push:
    paths:
      - "**/*.md"
      - ".vale.ini"
      - ".markdownlint.json"

jobs:
  doclint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Markdownlint ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint "**/*.md" --ignore node_modules

      # ---------- Codespell ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: |
          codespell \
            --ignore-words-list="crate,fo,ba,teh" \
            --skip="./node_modules,./.git,./styles" \
            --quiet-level=2

      # ---------- Vale (install latest release) ----------
      - name: Install Vale
        shell: bash
        run: |
          set -euo pipefail
          url=$(curl -s https://api.github.com/repos/errata-ai/vale/releases/latest \
            | grep browser_download_url \
            | grep Linux_64-bit.tar.gz \
            | cut -d '"' -f 4)
          curl -L "$url" -o vale.tar.gz
          tar -xzf vale.tar.gz
          sudo mv vale*/vale /usr/local/bin/vale
          vale -v
      - name: Run Vale
        run: vale .
