name: Documentation Quality

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  doclint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- Markdownlint ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md" --ignore node_modules

      # ---------- Codespell ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: |
          codespell \
            --ignore-words-list="crate,fo,ba,teh" \
            --skip="./node_modules,./.git,./styles" \
            --quiet-level=2

      # ---------- Vale (install/sync via action, no reviewdog UI) ----------
      - name: Setup Vale
        uses: errata-ai/vale-action@v2
        with:
          files: .
          reporter: local               # bypass reviewdog UI
          fail_on_error: false          # don't fail even if issues are found
          level: error                  # keep noise low during setup

      # ---------- Vale (CLI, non-blocking) ----------
      - name: Run Vale (non-blocking)
        run: |
          vale --version
          # Uses your .vale.ini; --no-exit prevents non-zero exit when issues exist
          vale --config=.vale.ini --no-exit .
