name: Documentation Quality

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  doclint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Markdownlint ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint "**/*.md" --ignore node_modules

      # ---------- Codespell ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: |
          codespell \
            --ignore-words-list="crate,fo,ba,teh" \
            --skip="./node_modules,./.git,./styles" \
            --quiet-level=2

      # ---------- Vale (style & grammar) ----------
      - name: Vale (style & grammar)
        uses: errata-ai/vale-action@v2
        with:
          files: .
          vale_flags: "--config=.vale.ini --no-exit"  # don't fail even if issues
          reporter: github-check                      # ✅ supported by reviewdog
          fail_on_error: false
          level: error                                # show only errors for now
          filter_mode: nofilter
